spring:
  application:
    name: broadcast-webhooks
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false

app:
  encryption:
    key: ${ENCRYPTION_KEY}

stripe:
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
